# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobilenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('emailcode', models.CharField(blank=True, max_length=200, null=True)),
                ('smscode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
