# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180716_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='emailcode',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='smscode',
        ),
    ]
